version: '3.4'
services:
  customer-crud:
    image: customer-crud
    restart: always
    build: .
    working_dir: /customer-crud
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    networks:
      - customer-network
networks:
    customer-network:
        driver: bridge