version: '3.4'
services:
  customer-crud:
    image: jonathandso/customer-crud
    restart: always
    build: .
    working_dir: /customer-crud
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./customer-crud:/customer-crud
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - customer-network
networks:
    customer-network:
        driver: bridge